/*
 * Implement actual methods of the interface that is defined at `interface.js`.
 * The signature of these method should be same between server and client,
 * it is the best to share the `interfac.js` file between of them.
 */

/**
 * Define `add` method that adds two numbers. This would be served via RESTful
 * API, that a HTTP handler is generated by `rpc` module.
 *
 * Unlike `interface.js`, it should have the actual implementation at a method.
 */
module.exports.add = (a, b) => a + b;
